"""Deterministic user-facing language and terminology catalog."""

from __future__ import annotations

from typing import Any


DEFAULT_LANGUAGE = "ko"
SUPPORTED_LANGUAGES = ("ko", "ja", "en")


UX_TEXT: dict[str, dict[str, str]] = {
    "ko": {
        "state.ready": "진행 가능",
        "state.needs_input": "입력 필요",
        "state.needs_confirmation": "확인 필요",
        "state.blocked": "진행할 수 없음",
        "state.completed": "완료",
        "state.recovery_required": "복구 필요",
        "state.review": "검토 필요",
        "section.state": "상태",
        "section.summary": "요약",
        "section.reason": "이유",
        "section.context": "참고",
        "section.next_actions": "다음 작업",
        "section.changed": "변경된 항목",
        "section.unchanged": "변경되지 않은 항목",
        "section.problem": "문제",
        "section.current_state": "현재 상태",
        "section.available_actions": "가능한 작업",
        "section.selection": "선택",
        "section.next_command": "다음 명령",
        "section.track": "지원 경로",
        "section.target_role": "희망 직종",
        "section.onboarding": "온보딩",
        "section.setup": "설정",
        "section.workspace": "취업 준비 작업공간",
        "section.pending": "확인 대기 항목",
        "section.unknown": "확인되지 않음 (Unknown)",
        "section.conflict": "정보 충돌 (Conflict)",
        "concept.canonical_state": "확정된 경력 정보",
        "concept.career_record": "경력 기록",
        "concept.review_queue": "확인 대기 목록",
        "concept.workspace_projection": "작업공간에 반영된 정보",
        "concept.original_document": "원본 문서",
        "concept.heartbeat": "상태 점검",
        "concept.proposal": "확인 대기 항목",
        "concept.pending_proposal": "확인 대기 중인 항목",
        "concept.queue": "대기 목록",
        "concept.workspace": "취업 준비 작업공간",
        "concept.projection": "작업공간에 반영된 정보",
        "concept.restore_state": "저장된 상태로 복구",
        "action.review_proposal": "내용 확인",
        "action.confirm_event": "확정하기",
        "action.confirm_context": "기준 정보로 확정",
        "action.review_heartbeat": "확인 완료로 처리",
        "action.review_queue_item": "확인하기",
        "action.keep_pending": "계속 대기",
        "action.keep_unknown": "확인되지 않은 상태 유지",
        "action.keep_conflict": "충돌 상태 유지",
        "action.inspect_status": "현재 상태 확인",
        "action.inspect_profile": "개인 프로필 확인",
        "action.inspect_context": "공유 정보 확인",
        "action.inspect_unknown": "확인되지 않은 정보 살펴보기",
        "action.inspect_conflict": "충돌한 정보 살펴보기",
        "action.inspect_workspace": "사용할 작업공간 선택",
        "action.inspect_workspace_state": "작업공간과 지원 현황 확인",
        "action.complete_setup": "설정 완료",
        "action.complete_required_setup": "필수 설정 완료",
        "action.run_doctor": "설정 문제 확인",
        "action.run_doctor_fix": "문제 확인 후 복구",
        "action.provide_evidence": "근거를 보완한 뒤 다시 시도",
        "action.provide_matching_evidence": "맞는 근거를 보완한 뒤 다시 시도",
        "action.restore_state": "저장된 상태로 복구",
        "action.choose_state_version": "저장된 상태 버전 선택",
        "action.retry": "입력을 확인하고 다시 시도",
        "action.exit": "종료",
        "action.start_task": "사용자가 말한 작업 시작",
        "action.review_proposals": "확인 대기 항목 보기",
        "action.approve_proposal": "확인 대기 항목 확정",
        "action.confirmation_required": "확인 필요",
        "summary.setup_needs_input": "Career Agent 설정에 프로필 입력이 필요합니다.",
        "summary.setup_blocked": "Career Agent 설정이 문제로 중단되었습니다.",
        "summary.setup_ready": "Career Agent 설정이 완료되었습니다.",
        "summary.guided_ready": "현재 상태에서 가능한 작업입니다.",
        "summary.doctor_blocked": "설정 또는 작업공간에 해결할 문제가 있습니다.",
        "summary.doctor_warning": "확인할 경고가 있습니다.",
        "summary.doctor_ok": "점검을 통과했습니다.",
        "summary.status_needs_track": "지원 경로를 먼저 정해야 합니다.",
        "summary.status_pending": "확인을 기다리는 항목이 있습니다.",
        "summary.status_pending_count": "{count}개의 확인 대기 항목이 있습니다.",
        "summary.status_ready": "다음 작업을 진행할 수 있습니다.",
        "summary.operation_pending": "확인 대기 항목이 만들어졌습니다.",
        "summary.heartbeat_pending": "상태 점검 결과가 확인 대기 중입니다.",
        "summary.operation_complete": "작업이 완료되었습니다.",
        "summary.proposal_review": "확정하기 전에 이 항목을 확인하세요.",
        "summary.proposal_reviewed": "항목 확인이 완료되었습니다.",
        "summary.no_pending": "확인 대기 항목이 없습니다.",
        "summary.approval_event": "내용이 경력 기록에 반영되었습니다.",
        "summary.approval_queue_only": "상태 점검 결과를 확인 완료로 처리했습니다.",
        "summary.restore_complete": "저장된 상태로 복구했습니다.",
        "summary.private_store_ready": "개인 문서 보관함 작업이 완료되었습니다.",
        "summary.read_only": "확인할 수 있는 정보입니다.",
        "summary.operation_not_completed": "작업을 완료하지 못했습니다.",
        "summary.guided_title": "Career Agent 안내",
        "reason.setup_required": "필수 설정 항목을 입력해야 합니다.",
        "reason.setup_complete": "Vault와 프로필 점검을 통과했습니다.",
        "reason.setup_blocked": "설정 단계는 끝났지만 해결할 문제가 남아 있습니다.",
        "reason.guided_confirmation": "현재 상태를 확인한 뒤 저장 작업을 명시적으로 확인하세요.",
        "reason.pending_proposal": "확인 대기 항목은 명시적으로 확정하기 전까지 확정된 정보가 아닙니다.",
        "reason.review_required": "확인해야 할 정보 상태가 하나 이상 있습니다.",
        "reason.guided_ready": "가능한 작업은 현재 확정된 상태에서 정해집니다.",
        "reason.doctor_error": "보고된 문제를 확인해야 다음 작업을 진행할 수 있습니다.",
        "reason.doctor_warning": "Vault는 사용할 수 있지만 프로필 또는 정보 확인이 남아 있습니다.",
        "reason.doctor_ok": "막히는 점검 결과가 없습니다.",
        "reason.status_ready": "현재 상태를 막는 확인 대기 항목이 없습니다.",
        "reason.operation_pending": "명시적으로 확정하기 전까지 이 항목은 확정된 정보가 아닙니다.",
        "reason.heartbeat_pending": "확인 완료로 처리해도 확정된 경력 정보는 바뀌지 않고 확인 대기 목록만 정리됩니다.",
        "reason.operation_complete": "기존 작업이 문제없이 끝났습니다.",
        "reason.proposal_review": "이 항목은 명시적으로 확정하기 전까지 초안입니다.",
        "reason.proposal_reviewed": "상태만 표시했으며 정보는 바꾸지 않았습니다.",
        "reason.no_pending": "현재 목록에 확인 대기 항목이 없습니다.",
        "reason.approval_event": "내용과 근거를 확인한 뒤 경력 기록에 반영했습니다.",
        "reason.approval_queue_only": "확인 대기 목록만 정리했으며 확정된 경력 정보는 바뀌지 않았습니다.",
        "reason.restore_complete": "현재 상태만 복구했으며 기록된 이력은 보존했습니다.",
        "reason.read_only": "이 작업은 확정된 경력 정보를 바꾸지 않았습니다.",
        "reason.private_store": "개인 문서 보관함의 경계를 유지했습니다.",
        "reason.operation_blocked": "현재 작업은 진행할 수 없습니다.",
        "disclosure.vault": "Vault에는 승인된 개인 경력 정보가 안전하게 저장됩니다.",
        "disclosure.approval": "확정하기 전에는 이 항목이 경력 정보에 반영되지 않습니다.",
        "disclosure.event_approval": "확정하기 전에 내용과 근거를 확인하세요. 확정하면 이 내용이 경력 기록에 반영됩니다.",
        "disclosure.heartbeat": "상태 점검 결과를 확인 완료로 처리해도 확정된 경력 정보는 바뀌지 않고 확인 대기 목록만 정리됩니다.",
        "disclosure.workspace": "작업공간은 취업 준비와 지원 현황을 관리하는 곳입니다.",
        "disclosure.unknown": "확인되지 않음 (Unknown)은 검증된 근거가 부족하다는 뜻입니다.",
        "disclosure.conflict": "정보 충돌 (Conflict)은 확인된 근거가 서로 맞지 않는다는 뜻이며 다른 강점으로 상쇄되지 않습니다.",
        "disclosure.restore": "저장된 상태로 복구하는 작업은 일반적인 실행 취소가 아니며 누적 기록을 되돌리지 않습니다.",
        "disclosure.private_store": "문서는 저장소 밖의 개인 보관함에 보관되며 자동으로 확정된 경력 정보가 되지 않습니다.",
        "effect.canonical_state": "확정된 경력 정보",
        "effect.career_state": "확정된 경력 정보",
        "effect.approved_event": "확정된 경력 기록",
        "effect.approved_event_canonical": "확정된 경력 기록",
        "effect.workspace_pipeline": "작업공간 지원 현황",
        "effect.original_document": "원본 문서",
        "effect.current_snapshot": "현재 상태",
        "effect.events": "기록된 이력",
        "effect.proposals": "확인 대기 목록",
        "effect.workspace": "작업공간 지원 현황",
        "effect.vault_profile": "Vault 프로필 설정",
        "effect.profile_setup": "프로필 설정",
        "effect.guided_operation": "선택한 작업",
        "effect.private_store": "개인 문서 보관함과 메타데이터",
        "effect.source_file": "원본 파일",
        "effect.personal_profile_canonical": "개인 프로필과 확정된 경력 정보",
        "heartbeat.deadline_action": "마감 확인: {key}",
        "event.approval_instruction": "근거를 확인한 뒤 확정하기",
        "event.title": "사용자가 말한 경력 기록",
        "chat.track_question": "지원 경로를 shinsotsu 또는 chuto 중에서 알려주세요.",
        "chat.track_retry": "지원 경로를 알려주시거나 career-profile.toml에 직접 설정해주세요.",
        "chat.graduation_question": "shinsotsu 경로에서 경력 기록을 만들려면 profile.graduation_year가 필요합니다.",
        "chat.graduation_retry": "career-profile.toml에 profile.graduation_year를 직접 설정해주세요.",
        "chat.graduation_hint": "메시지에서 {year}년 졸업으로 읽었습니다. 맞으면 다음을 실행해주세요: {command}",
        "chat.intent_question": "지금 가장 먼저 정리하려는 것은 무엇인가요?",
        "chat.intent_options": "자기분석 / 職務経歴書 / 求人 확인 / 応募 / 企業研究 / 면접 중에서 알려주세요.",
        "chat.intent_retry": "위 항목 중 하나로 답하시거나, 시작하려는 작업을 한 문장으로 적어주세요.",
        "error.guided_choice": "가능한 작업 번호나 이름을 선택해주세요.",
        "error.guided_action": "이 작업은 현재 안내 화면에서 실행할 수 없습니다.",
        "error.setup_track": "guided 설정에는 --track shinsotsu 또는 --track chuto가 필요합니다.",
        "error.setup_graduation": "shinsotsu 설정에는 --graduation-year가 필요합니다.",
        "error.guided_task": "사용자가 말한 작업을 --message로 입력해주세요.",
        "error.guided_approval": "확인 대기 항목이 하나인지 확인하거나 --proposal-id를 지정해주세요.",
        "error.guided_version": "저장된 상태를 복구하려면 --version을 지정해주세요.",
        "error.confirm_command": "저장하기 전에 명시적으로 확인해야 합니다.",
        "error.generic": "입력을 확인하고 다시 시도해주세요.",
        "guided.track_unset": "설정되지 않음",
        "guided.target_role_unset": "아직 확인되지 않음 (Unknown)",
        "guided.onboarding_active": "진행 중",
        "guided.onboarding_done": "완료",
        "guided.setup_complete": "완료",
        "guided.setup_required": "필요",
        "guided.workspace_unresolved": "확인되지 않음",
        "guided.no_blockers": "없음",
        "guided.confirmation_suffix": " (확인 필요)",
        "guided.prompt": "작업을 선택하세요 (번호 또는 이름, Enter로 종료): ",
    },
    "ja": {
        "state.ready": "実行可能",
        "state.needs_input": "入力が必要",
        "state.needs_confirmation": "確認が必要",
        "state.blocked": "実行できません",
        "state.completed": "完了",
        "state.recovery_required": "復旧が必要",
        "state.review": "要確認",
        "section.state": "状態",
        "section.summary": "概要",
        "section.reason": "理由",
        "section.context": "参考情報",
        "section.next_actions": "次の操作",
        "section.changed": "変更された項目",
        "section.unchanged": "変更されない項目",
        "section.problem": "問題",
        "section.current_state": "現在の状態",
        "section.available_actions": "利用できる操作",
        "section.selection": "選択",
        "section.next_command": "次のコマンド",
        "section.track": "応募区分",
        "section.target_role": "希望職種",
        "section.onboarding": "オンボーディング",
        "section.setup": "設定",
        "section.workspace": "就職活動ワークスペース",
        "section.pending": "確認待ち項目",
        "section.unknown": "未確認 (Unknown)",
        "section.conflict": "情報の矛盾 (Conflict)",
        "concept.canonical_state": "確定済みのキャリア情報",
        "concept.career_record": "キャリアの記録",
        "concept.review_queue": "確認待ち一覧",
        "concept.workspace_projection": "就職活動ワークスペースに反映された情報",
        "concept.original_document": "元の文書",
        "concept.heartbeat": "状態チェック",
        "concept.proposal": "確認待ち項目",
        "concept.pending_proposal": "確認待ちの項目",
        "concept.queue": "確認待ち一覧",
        "concept.workspace": "就職活動ワークスペース",
        "concept.projection": "ワークスペースへの反映情報",
        "concept.restore_state": "保存済み状態に復旧",
        "action.review_proposal": "内容を確認",
        "action.confirm_event": "確定する",
        "action.confirm_context": "基準情報として確定する",
        "action.review_heartbeat": "確認済みにする",
        "action.review_queue_item": "確認する",
        "action.keep_pending": "保留のままにする",
        "action.keep_unknown": "未確認のままにする",
        "action.keep_conflict": "矛盾した状態のままにする",
        "action.inspect_status": "現在の状態を確認",
        "action.inspect_profile": "個人プロフィールを確認",
        "action.inspect_context": "共有情報を確認",
        "action.inspect_unknown": "未確認の情報を確認",
        "action.inspect_conflict": "矛盾した情報を確認",
        "action.inspect_workspace": "使用するワークスペースを選択",
        "action.inspect_workspace_state": "ワークスペースと応募状況を確認",
        "action.complete_setup": "設定を完了",
        "action.complete_required_setup": "必要な設定を完了",
        "action.run_doctor": "設定の問題を確認",
        "action.run_doctor_fix": "問題を確認して復旧",
        "action.provide_evidence": "根拠を補って再試行",
        "action.provide_matching_evidence": "一致する根拠を補って再試行",
        "action.restore_state": "保存済み状態に復旧",
        "action.choose_state_version": "保存済み状態のバージョンを選択",
        "action.retry": "入力を確認して再試行",
        "action.exit": "終了",
        "action.start_task": "ユーザーが説明した作業を開始",
        "action.review_proposals": "確認待ち項目を表示",
        "action.approve_proposal": "確認待ち項目を確定",
        "action.confirmation_required": "確認が必要",
        "summary.setup_needs_input": "Career Agentの設定にプロフィール入力が必要です。",
        "summary.setup_blocked": "Career Agentの設定が問題により停止しています。",
        "summary.setup_ready": "Career Agentの設定が完了しました。",
        "summary.guided_ready": "現在の状態で実行できる操作です。",
        "summary.doctor_blocked": "設定またはワークスペースに解決が必要な問題があります。",
        "summary.doctor_warning": "確認が必要な警告があります。",
        "summary.doctor_ok": "チェックを通過しました。",
        "summary.status_needs_track": "応募区分を先に決めてください。",
        "summary.status_pending": "確認を待っている項目があります。",
        "summary.status_pending_count": "確認待ち項目が{count}件あります。",
        "summary.status_ready": "次の操作に進めます。",
        "summary.operation_pending": "確認待ち項目を作成しました。",
        "summary.heartbeat_pending": "状態チェックの結果が確認待ちです。",
        "summary.operation_complete": "操作が完了しました。",
        "summary.proposal_review": "確定する前にこの項目を確認してください。",
        "summary.proposal_reviewed": "項目の確認が完了しました。",
        "summary.no_pending": "確認待ち項目はありません。",
        "summary.approval_event": "内容をキャリアの記録に反映しました。",
        "summary.approval_queue_only": "状態チェックの結果を確認済みにしました。",
        "summary.restore_complete": "保存済み状態に復旧しました。",
        "summary.private_store_ready": "個人文書保管庫の操作が完了しました。",
        "summary.read_only": "確認できる情報です。",
        "summary.operation_not_completed": "操作を完了できませんでした。",
        "summary.guided_title": "Career Agent ガイド",
        "reason.setup_required": "必須の設定項目を入力してください。",
        "reason.setup_complete": "Vaultとプロフィールのチェックを通過しました。",
        "reason.setup_blocked": "設定の書き込みは完了しましたが、解決が必要な問題が残っています。",
        "reason.guided_confirmation": "現在の状態を確認し、保存操作を明示的に確認してください。",
        "reason.pending_proposal": "確認待ち項目は明示的に確定するまで確定済み情報ではありません。",
        "reason.review_required": "確認が必要な情報状態があります。",
        "reason.guided_ready": "実行できる操作は現在の確定済み状態から決まります。",
        "reason.doctor_error": "次の操作に進む前に報告された問題を確認してください。",
        "reason.doctor_warning": "Vaultは利用できますが、プロフィールまたは情報の確認が残っています。",
        "reason.doctor_ok": "問題となるチェック結果はありません。",
        "reason.status_ready": "現在の状態を止めている確認待ち項目はありません。",
        "reason.operation_pending": "明示的に確定するまで、この項目は確定済み情報ではありません。",
        "reason.heartbeat_pending": "確認済みにしても確定済みのキャリア情報は変わらず、確認待ち一覧だけが整理されます。",
        "reason.operation_complete": "既存の操作が問題なく完了しました。",
        "reason.proposal_review": "この項目は明示的に確定するまで下書きです。",
        "reason.proposal_reviewed": "状態だけを表示し、情報は変更していません。",
        "reason.no_pending": "現在の一覧に確認待ち項目はありません。",
        "reason.approval_event": "内容と根拠を確認し、キャリアの記録に反映しました。",
        "reason.approval_queue_only": "確認待ち一覧だけを整理し、確定済みのキャリア情報は変更していません。",
        "reason.restore_complete": "現在の状態だけを復旧し、記録された履歴は保持しました。",
        "reason.read_only": "この操作では確定済みのキャリア情報は変更されません。",
        "reason.private_store": "個人文書保管庫の境界を維持しました。",
        "reason.operation_blocked": "現在の操作は実行できません。",
        "disclosure.vault": "Vaultには承認済みの個人キャリア情報が安全に保存されます。",
        "disclosure.approval": "確定するまで、この項目はキャリア情報に反映されません。",
        "disclosure.event_approval": "確定する前に内容と根拠を確認してください。確定すると、この内容がキャリアの記録に反映されます。",
        "disclosure.heartbeat": "状態チェックを確認済みにしても確定済みのキャリア情報は変わらず、確認待ち一覧だけが整理されます。",
        "disclosure.workspace": "ワークスペースは就職活動と応募状況を管理する場所です。",
        "disclosure.unknown": "未確認 (Unknown)とは、検証済みの根拠が不足している状態です。",
        "disclosure.conflict": "情報の矛盾 (Conflict)とは、確認済みの根拠が一致しない状態で、別の強みで相殺されません。",
        "disclosure.restore": "保存済み状態への復旧は通常の取り消しではなく、追記履歴を巻き戻しません。",
        "disclosure.private_store": "文書はリポジトリ外の個人保管庫に保存され、自動的に確定済み情報にはなりません。",
        "effect.canonical_state": "確定済みのキャリア情報",
        "effect.career_state": "確定済みのキャリア情報",
        "effect.approved_event": "確定済みのキャリア記録",
        "effect.approved_event_canonical": "確定済みのキャリア記録",
        "effect.workspace_pipeline": "ワークスペースの応募状況",
        "effect.original_document": "元の文書",
        "effect.current_snapshot": "現在の状態",
        "effect.events": "記録された履歴",
        "effect.proposals": "確認待ち一覧",
        "effect.workspace": "ワークスペースの応募状況",
        "effect.vault_profile": "Vaultプロフィール設定",
        "effect.profile_setup": "プロフィール設定",
        "effect.guided_operation": "選択した操作",
        "effect.private_store": "個人文書保管庫とメタデータ",
        "effect.source_file": "元のファイル",
        "effect.personal_profile_canonical": "個人プロフィールと確定済みのキャリア情報",
        "heartbeat.deadline_action": "期限を確認: {key}",
        "event.approval_instruction": "根拠を確認してから確定する",
        "event.title": "ユーザーが説明したキャリアの記録",
        "chat.track_question": "応募区分をshinsotsuまたはchutoから指定してください。",
        "chat.track_retry": "応募区分を返信するか、career-profile.tomlに直接設定してください。",
        "chat.graduation_question": "shinsotsuでキャリアの記録を作るにはprofile.graduation_yearが必要です。",
        "chat.graduation_retry": "career-profile.tomlにprofile.graduation_yearを直接設定してください。",
        "chat.graduation_hint": "メッセージから{year}年卒と読み取りました。合っていれば次を実行してください: {command}",
        "chat.intent_question": "今いちばん先に整理したいことは何ですか。",
        "chat.intent_options": "自己分析 / 職務経歴書 / 求人の確認 / 応募 / 企業研究 / 面接 から選んでください。",
        "chat.intent_retry": "上のいずれかで答えるか、始めたい作業を一文で書いてください。",
        "error.guided_choice": "利用できる操作の番号または名前を選択してください。",
        "error.guided_action": "この操作は現在のガイド画面から実行できません。",
        "error.setup_track": "guided設定には--track shinsotsuまたは--track chutoが必要です。",
        "error.setup_graduation": "shinsotsuの設定には--graduation-yearが必要です。",
        "error.guided_task": "ユーザーが説明した作業を--messageで入力してください。",
        "error.guided_approval": "確認待ち項目が1件か確認するか、--proposal-idを指定してください。",
        "error.guided_version": "保存済み状態を復旧するには--versionを指定してください。",
        "error.confirm_command": "保存する前に明示的な確認が必要です。",
        "error.generic": "入力を確認して再試行してください。",
        "guided.track_unset": "未設定",
        "guided.target_role_unset": "未確認 (Unknown)",
        "guided.onboarding_active": "進行中",
        "guided.onboarding_done": "完了",
        "guided.setup_complete": "完了",
        "guided.setup_required": "必要",
        "guided.workspace_unresolved": "未確認",
        "guided.no_blockers": "なし",
        "guided.confirmation_suffix": " (確認が必要)",
        "guided.prompt": "操作を選択してください（番号または名前、Enterで終了）: ",
    },
    "en": {
        "state.ready": "Ready",
        "state.needs_input": "Input needed",
        "state.needs_confirmation": "Needs confirmation",
        "state.blocked": "Blocked",
        "state.completed": "Completed",
        "state.recovery_required": "Recovery needed",
        "state.review": "Review needed",
        "section.state": "State",
        "section.summary": "Summary",
        "section.reason": "Reason",
        "section.context": "Context",
        "section.next_actions": "Next actions",
        "section.changed": "Changed",
        "section.unchanged": "Unchanged",
        "section.problem": "Problem",
        "section.current_state": "Current state",
        "section.available_actions": "Available actions",
        "section.selection": "Selection",
        "section.next_command": "Next command",
        "section.track": "Track",
        "section.target_role": "Target role",
        "section.onboarding": "Onboarding",
        "section.setup": "Setup",
        "section.workspace": "Job-search workspace",
        "section.pending": "Review items",
        "section.unknown": "Unknown",
        "section.conflict": "Conflict",
        "concept.canonical_state": "confirmed career information",
        "concept.career_record": "career record",
        "concept.review_queue": "review queue",
        "concept.workspace_projection": "information shown in your job-search workspace",
        "concept.original_document": "original document",
        "concept.heartbeat": "status check",
        "concept.proposal": "review item",
        "concept.pending_proposal": "pending review item",
        "concept.queue": "review queue",
        "concept.workspace": "job-search workspace",
        "concept.projection": "information shown in your job-search workspace",
        "concept.restore_state": "restore saved state",
        "action.review_proposal": "Review details",
        "action.confirm_event": "Confirm",
        "action.confirm_context": "Confirm as baseline information",
        "action.review_heartbeat": "Mark reviewed",
        "action.review_queue_item": "Review item",
        "action.keep_pending": "Keep pending",
        "action.keep_unknown": "Keep Unknown",
        "action.keep_conflict": "Keep Conflict",
        "action.inspect_status": "View current status",
        "action.inspect_profile": "View personal profile",
        "action.inspect_context": "View shared information",
        "action.inspect_unknown": "Review unverified information",
        "action.inspect_conflict": "Review conflicting information",
        "action.inspect_workspace": "Choose a workspace",
        "action.inspect_workspace_state": "View workspace and application status",
        "action.complete_setup": "Complete setup",
        "action.complete_required_setup": "Complete required setup",
        "action.run_doctor": "Inspect setup problems",
        "action.run_doctor_fix": "Inspect and repair problems",
        "action.provide_evidence": "Add evidence and retry",
        "action.provide_matching_evidence": "Add matching evidence and retry",
        "action.restore_state": "Restore saved state",
        "action.choose_state_version": "Choose a saved state version",
        "action.retry": "Review the input and retry",
        "action.exit": "Exit",
        "action.start_task": "Start a user-described task",
        "action.review_proposals": "View review items",
        "action.approve_proposal": "Confirm the review item",
        "action.confirmation_required": "confirmation required",
        "summary.setup_needs_input": "Career Agent setup needs profile input.",
        "summary.setup_blocked": "Career Agent setup is blocked by a problem.",
        "summary.setup_ready": "Career Agent setup is complete.",
        "summary.guided_ready": "These actions are available from the current state.",
        "summary.doctor_blocked": "Setup or workspace problems need attention.",
        "summary.doctor_warning": "There are warnings to review.",
        "summary.doctor_ok": "Checks passed.",
        "summary.status_needs_track": "Choose a track before continuing.",
        "summary.status_pending": "Some items are waiting for review.",
        "summary.status_pending_count": "{count} review item(s) are waiting.",
        "summary.status_ready": "You can continue with the next action.",
        "summary.operation_pending": "A review item was created.",
        "summary.heartbeat_pending": "A status-check result is waiting for review.",
        "summary.operation_complete": "The operation is complete.",
        "summary.proposal_review": "Review this item before confirming.",
        "summary.proposal_reviewed": "Item review is complete.",
        "summary.no_pending": "There are no review items.",
        "summary.approval_event": "The information was added to your career record.",
        "summary.approval_queue_only": "The status-check result was marked reviewed.",
        "summary.restore_complete": "The saved state was restored.",
        "summary.private_store_ready": "The private document-store operation is complete.",
        "summary.read_only": "This information is available to review.",
        "summary.operation_not_completed": "The operation was not completed.",
        "summary.guided_title": "Career Agent guide",
        "reason.setup_required": "Required setup fields are missing.",
        "reason.setup_complete": "The Vault and profile passed their checks.",
        "reason.setup_blocked": "The setup write finished, but a blocking problem remains.",
        "reason.guided_confirmation": "Review the current state, then explicitly confirm before saving.",
        "reason.pending_proposal": "A review item is not confirmed information until you explicitly confirm it.",
        "reason.review_required": "One or more information states need review.",
        "reason.guided_ready": "Available actions come from the current confirmed state.",
        "reason.doctor_error": "Review the reported problems before continuing.",
        "reason.doctor_warning": "The Vault is usable, but profile or information warnings remain.",
        "reason.doctor_ok": "No blocking doctor findings were reported.",
        "reason.status_ready": "No review item is blocking the current status.",
        "reason.operation_pending": "This item is not confirmed information until explicitly confirmed.",
        "reason.heartbeat_pending": "Marking it reviewed does not change your confirmed career information; it only clears the review queue.",
        "reason.operation_complete": "The existing operation completed successfully.",
        "reason.proposal_review": "This item remains a draft until explicitly confirmed.",
        "reason.proposal_reviewed": "Only the status was shown; no information changed.",
        "reason.no_pending": "There are no review items in the current list.",
        "reason.approval_event": "The details and evidence were checked before updating the career record.",
        "reason.approval_queue_only": "Only the review queue was cleared; confirmed career information did not change.",
        "reason.restore_complete": "Only the current state was restored; recorded history was kept.",
        "reason.read_only": "This operation did not change confirmed career information.",
        "reason.private_store": "Private document-store boundaries were preserved.",
        "reason.operation_blocked": "The current operation cannot continue.",
        "disclosure.vault": "The Vault stores approved personal career information safely.",
        "disclosure.approval": "This item does not become part of your career information until confirmed.",
        "disclosure.event_approval": "Review the details and evidence before confirming. Once confirmed, this information becomes part of your career record.",
        "disclosure.heartbeat": "Marking a status-check result reviewed does not change your confirmed career information; it only clears the review queue.",
        "disclosure.workspace": "The workspace manages job-search and application status.",
        "disclosure.unknown": "Unknown means verified evidence is missing.",
        "disclosure.conflict": "Conflict means confirmed evidence disagrees; another strength does not offset it.",
        "disclosure.restore": "Restore saved state is recovery, not a general undo, and does not rewind append-only history.",
        "disclosure.private_store": "The document stays in a private store outside the repository and is not automatically confirmed career information.",
        "effect.canonical_state": "confirmed career information",
        "effect.career_state": "confirmed career information",
        "effect.approved_event": "confirmed career record",
        "effect.approved_event_canonical": "confirmed career record",
        "effect.workspace_pipeline": "workspace application status",
        "effect.original_document": "original document",
        "effect.current_snapshot": "current state",
        "effect.events": "recorded history",
        "effect.proposals": "review queue",
        "effect.workspace": "workspace application status",
        "effect.vault_profile": "Vault profile setup",
        "effect.profile_setup": "profile setup",
        "effect.guided_operation": "selected operation",
        "effect.private_store": "private document store and metadata",
        "effect.source_file": "source file",
        "effect.personal_profile_canonical": "personal profile and confirmed career information",
        "heartbeat.deadline_action": "Check deadline: {key}",
        "event.approval_instruction": "Review evidence before confirming",
        "event.title": "User-described career record",
        "chat.track_question": "Please specify shinsotsu or chuto as your track.",
        "chat.track_retry": "Reply with your track or set it directly in career-profile.toml.",
        "chat.graduation_question": "profile.graduation_year is required for a shinsotsu career record.",
        "chat.graduation_retry": "Set profile.graduation_year directly in career-profile.toml.",
        "chat.graduation_hint": "Read {year} as your graduation year from your message. If that is right, run: {command}",
        "chat.intent_question": "What do you want to work on first?",
        "chat.intent_options": "Choose one: self-analysis, 職務経歴書, reviewing a job description, apply for a role, company research, or interview prep.",
        "chat.intent_retry": "Reply with one of those, or describe the task you want to start in one sentence.",
        "error.guided_choice": "Choose an available action number or name.",
        "error.guided_action": "This action cannot be run from the current guide.",
        "error.setup_track": "Guided setup needs --track shinsotsu or --track chuto.",
        "error.setup_graduation": "Shinsotsu setup needs --graduation-year.",
        "error.guided_task": "Enter the user-described task with --message.",
        "error.guided_approval": "Confirm that there is one review item, or specify --proposal-id.",
        "error.guided_version": "Specify --version to restore a saved state.",
        "error.confirm_command": "Explicit confirmation is required before saving.",
        "error.generic": "Review the input and retry.",
        "guided.track_unset": "not set",
        "guided.target_role_unset": "not confirmed yet (Unknown)",
        "guided.onboarding_active": "in progress",
        "guided.onboarding_done": "complete",
        "guided.setup_complete": "complete",
        "guided.setup_required": "required",
        "guided.workspace_unresolved": "not resolved",
        "guided.no_blockers": "none",
        "guided.confirmation_suffix": " (confirmation required)",
        "guided.prompt": "Choose an action (number or name; Enter exits): ",
    },
}


def normalize_language(value: Any) -> str:
    raw = str(value or "").casefold().replace("_", "-")
    base = raw.split("-", 1)[0]
    return base if base in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def text(language: Any, translation_key: str, **values: Any) -> str:
    """Resolve a catalog key; missing keys fail loudly instead of leaking identifiers."""
    locale = normalize_language(language)
    template = UX_TEXT.get(locale, {}).get(translation_key) or UX_TEXT["en"].get(translation_key) or UX_TEXT[DEFAULT_LANGUAGE].get(translation_key)
    if template is None:
        raise KeyError(f"missing UX translation: {translation_key}")
    return template.format(**values)


def catalog_keys() -> set[str]:
    return set(UX_TEXT[DEFAULT_LANGUAGE])


def action_label(language: Any, action_id: str, *, proposal_kind: str | None = None) -> str:
    key = {
        "review_proposal": "action.review_proposal",
        "approve_proposal": {
            "event": "action.confirm_event",
            "career_context": "action.confirm_context",
            "heartbeat": "action.review_heartbeat",
        }.get(proposal_kind, "action.review_queue_item"),
        "keep_pending": "action.keep_pending",
        "keep_unknown": "action.keep_unknown",
        "keep_conflict": "action.keep_conflict",
        "inspect_status": "action.inspect_status",
        "inspect_profile": "action.inspect_profile",
        "inspect_context": "action.inspect_context",
        "inspect_unknown": "action.inspect_unknown",
        "inspect_conflict": "action.inspect_conflict",
        "inspect_workspace": "action.inspect_workspace",
        "inspect_workspace_state": "action.inspect_workspace_state",
        "complete_setup": "action.complete_setup",
        "run_setup": "action.complete_setup",
        "complete_required_setup": "action.complete_required_setup",
        "run_doctor": "action.run_doctor",
        "provide_evidence": "action.provide_evidence",
        "provide_matching_evidence": "action.provide_matching_evidence",
        "choose_state_version": "action.choose_state_version",
        "retry": "action.retry",
        "restore_state": "action.restore_state",
        "exit": "action.exit",
        "start_task": "action.start_task",
        "review_proposals": "action.review_proposals",
        "inspect_private_store": "action.inspect_context",
    }.get(action_id, "action.review_queue_item")
    return text(language, key)


def state_label(language: Any, state: Any) -> str:
    return text(language, f"state.{state}" if f"state.{state}" in UX_TEXT["en"] else "state.blocked")


# Every string a command may put in `effects.changed` / `effects.unchanged`, mapped to the phrase
# the user reads. Module level rather than local so `test_ux.py` can assert that ux.py produces
# nothing outside this map: an effect without an entry is returned unchanged, which prints an
# internal term like `canonical state` in place of a translation and fails no other check.
EFFECT_ALIASES = {
    "canonical state": "effect.canonical_state",
    "canonical state until approval": "effect.canonical_state",
    "canonical career state": "effect.career_state",
    "canonical career facts": "effect.career_state",
    "approved event/canonical state": "effect.approved_event_canonical",
    "approved event": "effect.approved_event",
    "workspace pipeline": "effect.workspace_pipeline",
    "original private document": "effect.original_document",
    "current state snapshot": "effect.current_snapshot",
    "events.jsonl": "effect.events",
    "proposals.jsonl": "effect.proposals",
    "vault/profile setup": "effect.vault_profile",
    "profile setup": "effect.profile_setup",
    "guided-selected operation": "effect.guided_operation",
    "private-store copy and metadata": "effect.private_store",
    "original source file": "effect.source_file",
    "personal profile and canonical state": "effect.personal_profile_canonical",
}


def effect_label(language: Any, value: Any) -> str:
    raw = str(value)
    return text(language, EFFECT_ALIASES[raw]) if raw in EFFECT_ALIASES else raw


def error_message(language: Any, code: str | None, fallback: str | None = None) -> str:
    key = {
        "INVALID_INPUT": "error.guided_choice",
        "SETUP_REQUIRED": "reason.setup_required",
        "PROPOSAL_NOT_FOUND": "reason.operation_blocked",
        "PROPOSAL_NOT_PENDING": "reason.operation_blocked",
        "EVIDENCE_REQUIRED": "action.provide_evidence",
        "EVIDENCE_MISMATCH": "action.provide_matching_evidence",
    }.get(str(code or ""), "reason.operation_blocked")
    return text(language, key) if key.startswith("reason.") or key.startswith("action.") else (fallback or text(language, "error.generic"))


def validate_catalog() -> list[str]:
    expected = catalog_keys()
    return [locale for locale in SUPPORTED_LANGUAGES if set(UX_TEXT[locale]) != expected]
