#!/usr/bin/env python3
"""Compatibility facade for the Career Agent runtime.

Every name the runtime has ever exported still resolves here, and nothing is implemented here. The
application layer lives in `command_line`, `dispatch` and the owner modules they call; the domain
layer lives where it always did. A new command is added by writing a function in an owner module
and one line in `dispatch`, never by editing this file, and `check_career_agent_boundaries.py`
fails the build if a definition reappears here.

`career_agent.py` aliases this module into `sys.modules`, so `import career_agent` keeps returning
the same historical surface -- including the names integrations bind to.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import sys
import uuid

from pathlib import Path
from typing import Any, Iterable, Mapping

_SHARED_ROOT = Path(__file__).resolve().parent.parent.parent / "_shared"
if str(_SHARED_ROOT) not in sys.path:
    sys.path.insert(0, str(_SHARED_ROOT))
import pipeline_store  # noqa: E402

from models import (  # noqa: E402
    CAREER_CONTEXT_FIELDS,
    CAREER_MODES,
    CAREER_STATUSES,
    CHUTO_STAGES,
    CONTEXT_KINDS,
    EMPLOYMENT_STATUSES,
    EVENT_STATUSES,
    EXPERIENCE_CONTEXT_KINDS,
    EXTERNAL_USE_STATES,
    FACT_CATEGORIES,
    PROJECT_EVENT_TYPE,
    PROJECT_STATUSES,
    JOB_SEARCH_STATES,
    PROFILE_AXES,
    WORK_EVENT_TYPE,
    PIPELINE_STAGE,
    REFERENCE_BY_STAGE,
    REQUIRED_CONTEXT_METADATA,
    REQUIRED_EVENT_FIELDS,
    SHINSOTSU_STAGES,
    SKILL_BY_STAGE,
    TRACKS,
    TRUSTED_SOURCE_TYPES,
    UNTRUSTED_DATA_MARKER,
    VAULT_DIRECTORIES,
    CareerError,
    as_text,
    default_state,
    employment_status_of,
    job_search_of,
    normalized_state,
)
from validation import (  # noqa: E402
    DATE_VALUE,
    NUMERIC_CLAIM,
    iso_date,
    validate_career_context,
    validate_event,
    validate_work_event,
)
from routing import (  # noqa: E402
    FLOW_REFERENCE,
    ROUTING,
    ROUTING_REFERENCE,
    _WORD_BOUNDARY_TERMS,
    active_search_intent,
    explicit_stage_alias,
    flow_phase_for,
    maintenance_intent,
    opportunity_review_intent,
    tanaoroshi_intent,
    review_closed_intent,
    transition_intent,
    flow_phase_ids,
    graduation_signal,
    infer_track,
    language_for,
    load_flow_reference,
    load_routing,
    matched_stage_alias,
    skill_context,
    stage_for,
    term_present,
)
from proposals import (  # noqa: E402
    make_experience_context_event,
    make_project_event,
    stated_career_mode,
    approval_action_for,
    list_proposals,
    make_event,
    proposal_summary,
    propose_career_context,
    propose_fact,
    review_proposal,
    run_chat,
)
from lifecycle import (  # noqa: E402
    review_work_event,
    approve as _lifecycle_approve,
    count_consecutive_safe_stops,
    record_failed_attempt,
    read_approval_transaction,
    recover_pending,
    restore_state,
    state_version_is_persisted,
    vault_lock,
)
from document import GENERATED_DOCUMENT_TYPES, document_model, fidelity_gate  # noqa: E402
from render import (  # noqa: E402
    RENDERER_VERSION,
    available_templates,
    manifest,
    outdated_reasons,
    render,
    resolve_template,
)
from projection import (  # noqa: E402
    clamp_career_mode,
    contexts_from_events,
    experiences_from_events,
    next_career_mode,
    project_timeline,
    projects_from_events,
    work_event_date,
    work_event_project_ids,
    _legacy_company_slug,
    apply_event_to_state,
    company_slug,
    migrate_pipeline_file,
    pipeline_file,
    upsert_pipeline_entry,
    workspace_path,
)
from persistence import (  # noqa: E402
    append_jsonl,
    atomic_write_text,
    read_json,
    read_jsonl,
    read_toml,
    toml_value,
    write_json,
    write_jsonl,
    write_toml,
)
from personal_timeline import (  # noqa: E402
    candidate_profile_values,
    document_states,
    historical_comparison,
    project,
    select_personal_context,
    timeline,
)
from private_store import (  # noqa: E402
    DOCUMENT_TYPES,
    PRIVATE_ENV,
    PrivateHome,
    documents as private_documents,
    import_document,
    initialize_private_home,
    private_doctor,
    resolve_private_home,
)
from vault import (  # noqa: E402
    HEADING,
    IGNORED_VAULT_DIRS,
    WIKILINK,
    CareerVault,
    context_eligible,
    index_vault_notes,
    initialize_vault,
    metadata_values,
    note_kind,
    parse_frontmatter,
    policy_template,
    profile_template,
    select_context,
    today,
    utc_now,
)
from ux import attach as project_ux, error_payload, render_human  # noqa: E402
from localization import normalize_language, text  # noqa: E402
from guided import (  # noqa: E402
    build_summary,
    derive_actions,
    guided_state,
    render_human as render_guided_human,
    resolve_choice,
)

# The application layer. These are re-exported, never defined here.
from command_line import _output_language, build_parser, main  # noqa: E402
from dispatch import _requires_approval_recovery, run_command, run_private_command  # noqa: E402
from diagnostics import doctor  # noqa: E402
from onboarding import (  # noqa: E402
    _invocation,
    _set_profile_axis_locked,
    complete_onboarding,
    DEFAULT_VAULT_PATH,
    set_profile_axis,
    setup,
)
from ingest import (  # noqa: E402
    choose_actions,
    decode_utf8,
    load_posting_records,
    normalize_posting,
    posting_key,
    read_stdin_utf8,
    run_discover,
    run_heartbeat,
    run_index,
)
from experiences import (  # noqa: E402
    add_context,
    add_project,
    latest_career_context,
    link_work_event,
    list_contexts,
    list_experiences,
    list_projects,
    pending_work_events,
    private_records,
    run_context,
    show_project_timeline,
    work_events,
)
from documents import (  # noqa: E402
    _canonical_revision,
    _pipeline_company,
    _read_document_file,
    build_document_model,
    check_document,
    render_document,
)
from views import (  # noqa: E402
    evidence_pool,
    maintenance_check,
    readiness,
    status,
    weekly_review,
    workspace_summary,
)
from approvals import (  # noqa: E402
    _pipeline_writer_for,
    _state_projector_for,
    approve,
    recover_approval,
)
from guided_flow import (  # noqa: E402
    _guided_result,
    _guided_selection,
    _guided_snapshot,
    _guided_workspace_fallback,
    run_guided,
)

# The compatibility surface, declared rather than inferred. Everything an integration, a test,
# or `import career_agent` has ever bound to is named here, so removing one is a visible edit
# instead of a silent consequence of moving code. Underscore names are included deliberately:
# they are private to this package but public to the callers that already reached for them.
__all__ = [
    "_canonical_revision",
    "_DOCUMENT_COMPATIBILITY_EXPORTS",
    "_guided_result",
    "_guided_selection",
    "_guided_snapshot",
    "_guided_workspace_fallback",
    "_invocation",
    "_legacy_company_slug",
    "_lifecycle_approve",
    "_LIFECYCLE_COMPATIBILITY_EXPORTS",
    "_MODEL_COMPATIBILITY_EXPORTS",
    "_output_language",
    "_PERSISTENCE_COMPATIBILITY_EXPORTS",
    "_pipeline_company",
    "_pipeline_writer_for",
    "_PROJECTION_COMPATIBILITY_EXPORTS",
    "_PROPOSAL_COMPATIBILITY_EXPORTS",
    "_read_document_file",
    "_requires_approval_recovery",
    "_ROUTING_COMPATIBILITY_EXPORTS",
    "_set_profile_axis_locked",
    "_state_projector_for",
    "_VAULT_COMPATIBILITY_EXPORTS",
    "_WORD_BOUNDARY_TERMS",
    "active_search_intent",
    "add_context",
    "add_project",
    "Any",
    "append_jsonl",
    "apply_event_to_state",
    "approval_action_for",
    "approve",
    "argparse",
    "as_text",
    "atomic_write_text",
    "available_templates",
    "build_document_model",
    "build_parser",
    "build_summary",
    "candidate_profile_values",
    "CAREER_CONTEXT_FIELDS",
    "CAREER_MODES",
    "CAREER_STATUSES",
    "CareerError",
    "CareerVault",
    "check_document",
    "choose_actions",
    "CHUTO_STAGES",
    "clamp_career_mode",
    "company_slug",
    "complete_onboarding",
    "context_eligible",
    "CONTEXT_KINDS",
    "contexts_from_events",
    "count_consecutive_safe_stops",
    "DATE_VALUE",
    "decode_utf8",
    "default_state",
    "DEFAULT_VAULT_PATH",
    "derive_actions",
    "doctor",
    "document_model",
    "document_states",
    "DOCUMENT_TYPES",
    "dt",
    "employment_status_of",
    "EMPLOYMENT_STATUSES",
    "error_payload",
    "EVENT_STATUSES",
    "evidence_pool",
    "EXPERIENCE_CONTEXT_KINDS",
    "experiences_from_events",
    "explicit_stage_alias",
    "EXTERNAL_USE_STATES",
    "FACT_CATEGORIES",
    "fidelity_gate",
    "flow_phase_for",
    "flow_phase_ids",
    "FLOW_REFERENCE",
    "GENERATED_DOCUMENT_TYPES",
    "graduation_signal",
    "guided_state",
    "hashlib",
    "HEADING",
    "historical_comparison",
    "IGNORED_VAULT_DIRS",
    "import_document",
    "index_vault_notes",
    "infer_track",
    "initialize_private_home",
    "initialize_vault",
    "iso_date",
    "Iterable",
    "job_search_of",
    "JOB_SEARCH_STATES",
    "json",
    "language_for",
    "latest_career_context",
    "link_work_event",
    "list_contexts",
    "list_experiences",
    "list_projects",
    "list_proposals",
    "load_flow_reference",
    "load_posting_records",
    "load_routing",
    "main",
    "maintenance_check",
    "maintenance_intent",
    "make_event",
    "make_experience_context_event",
    "make_project_event",
    "manifest",
    "Mapping",
    "matched_stage_alias",
    "metadata_values",
    "migrate_pipeline_file",
    "next_career_mode",
    "normalize_language",
    "normalize_posting",
    "normalized_state",
    "note_kind",
    "NUMERIC_CLAIM",
    "opportunity_review_intent",
    "os",
    "outdated_reasons",
    "parse_frontmatter",
    "Path",
    "pending_work_events",
    "pipeline_file",
    "PIPELINE_STAGE",
    "pipeline_store",
    "policy_template",
    "posting_key",
    "private_doctor",
    "private_documents",
    "PRIVATE_ENV",
    "private_records",
    "PrivateHome",
    "PROFILE_AXES",
    "profile_template",
    "project",
    "PROJECT_EVENT_TYPE",
    "PROJECT_STATUSES",
    "project_timeline",
    "project_ux",
    "projects_from_events",
    "proposal_summary",
    "propose_career_context",
    "propose_fact",
    "read_approval_transaction",
    "read_json",
    "read_jsonl",
    "read_stdin_utf8",
    "read_toml",
    "readiness",
    "record_failed_attempt",
    "recover_approval",
    "recover_pending",
    "REFERENCE_BY_STAGE",
    "render",
    "render_document",
    "render_guided_human",
    "render_human",
    "RENDERER_VERSION",
    "REQUIRED_CONTEXT_METADATA",
    "REQUIRED_EVENT_FIELDS",
    "resolve_choice",
    "resolve_private_home",
    "resolve_template",
    "restore_state",
    "review_closed_intent",
    "review_proposal",
    "review_work_event",
    "ROUTING",
    "ROUTING_REFERENCE",
    "run_chat",
    "run_command",
    "run_context",
    "run_discover",
    "run_guided",
    "run_heartbeat",
    "run_index",
    "run_private_command",
    "select_context",
    "select_personal_context",
    "set_profile_axis",
    "setup",
    "SHINSOTSU_STAGES",
    "show_project_timeline",
    "SKILL_BY_STAGE",
    "skill_context",
    "stage_for",
    "state_version_is_persisted",
    "stated_career_mode",
    "status",
    "sys",
    "tanaoroshi_intent",
    "term_present",
    "text",
    "timeline",
    "today",
    "toml_value",
    "TRACKS",
    "transition_intent",
    "TRUSTED_SOURCE_TYPES",
    "UNTRUSTED_DATA_MARKER",
    "upsert_pipeline_entry",
    "utc_now",
    "uuid",
    "validate_career_context",
    "validate_event",
    "validate_work_event",
    "VAULT_DIRECTORIES",
    "vault_lock",
    "weekly_review",
    "WIKILINK",
    "work_event_date",
    "work_event_project_ids",
    "WORK_EVENT_TYPE",
    "work_events",
    "workspace_path",
    "workspace_summary",
    "write_json",
    "write_jsonl",
    "write_toml",
]
_PROPOSAL_COMPATIBILITY_EXPORTS = (
    make_experience_context_event,
    make_project_event,
    stated_career_mode,
    approval_action_for,
    list_proposals,
    make_event,
    proposal_summary,
    propose_career_context,
    propose_fact,
    run_chat,
)

_LIFECYCLE_COMPATIBILITY_EXPORTS = (
    count_consecutive_safe_stops,
    record_failed_attempt,
    state_version_is_persisted,
)

_DOCUMENT_COMPATIBILITY_EXPORTS = (
    GENERATED_DOCUMENT_TYPES,
    RENDERER_VERSION,
    document_model,
    fidelity_gate,
    available_templates,
    manifest,
    outdated_reasons,
    render,
    resolve_template,
)

_PROJECTION_COMPATIBILITY_EXPORTS = (
    _legacy_company_slug,
    contexts_from_events,
    experiences_from_events,
    project_timeline,
    projects_from_events,
    work_event_date,
    work_event_project_ids,
    apply_event_to_state,
    clamp_career_mode,
    company_slug,
    migrate_pipeline_file,
    next_career_mode,
    pipeline_file,
    upsert_pipeline_entry,
    workspace_path,
)

_ROUTING_COMPATIBILITY_EXPORTS = (
    FLOW_REFERENCE,
    ROUTING,
    ROUTING_REFERENCE,
    _WORD_BOUNDARY_TERMS,
    active_search_intent,
    explicit_stage_alias,
    flow_phase_for,
    maintenance_intent,
    opportunity_review_intent,
    review_closed_intent,
    tanaoroshi_intent,
    transition_intent,
    flow_phase_ids,
    graduation_signal,
    infer_track,
    language_for,
    load_routing,
    matched_stage_alias,
    skill_context,
    stage_for,
    term_present,
)

_PERSISTENCE_COMPATIBILITY_EXPORTS = (
    atomic_write_text,
    read_json,
    read_toml,
    toml_value,
    write_json,
)

_VAULT_COMPATIBILITY_EXPORTS = (
    HEADING,
    IGNORED_VAULT_DIRS,
    WIKILINK,
    context_eligible,
    metadata_values,
    note_kind,
    parse_frontmatter,
    policy_template,
    profile_template,
)

_MODEL_COMPATIBILITY_EXPORTS = (
    CAREER_CONTEXT_FIELDS,
    CAREER_MODES,
    CAREER_STATUSES,
    CHUTO_STAGES,
    CONTEXT_KINDS,
    EMPLOYMENT_STATUSES,
    EVENT_STATUSES,
    EXTERNAL_USE_STATES,
    JOB_SEARCH_STATES,
    PROJECT_EVENT_TYPE,
    PROJECT_STATUSES,
    WORK_EVENT_TYPE,
    PIPELINE_STAGE,
    REFERENCE_BY_STAGE,
    REQUIRED_CONTEXT_METADATA,
    REQUIRED_EVENT_FIELDS,
    SHINSOTSU_STAGES,
    SKILL_BY_STAGE,
    TRACKS,
    TRUSTED_SOURCE_TYPES,
    UNTRUSTED_DATA_MARKER,
    VAULT_DIRECTORIES,
    CareerError,
    as_text,
    default_state,
    employment_status_of,
    job_search_of,
    normalized_state,
    validate_career_context,
    validate_event,
    validate_work_event,
    DATE_VALUE,
    NUMERIC_CLAIM,
)


if __name__ == "__main__":
    raise SystemExit(main())
