#!/usr/bin/env python3
"""Mark an action item done in data/pipeline.yml.

    python3 scripts/check_action.py <company-slug> <item-id>
    python3 scripts/check_action.py --list

Deliberately a user-run command rather than something the assistant does. The gate exists
because checklists got written and never acted on; if the assistant could tick the boxes,
it could clear its own gate without the work ever happening. Reading the count is the
assistant's job, flipping the bit is yours.

Rewrites pipeline.yml through PyYAML, so comments in that file are not preserved. It is
generated by the skills, so it should not have any.
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

_SHARED_ROOT = Path(__file__).resolve().parent.parent / "_shared"
if str(_SHARED_ROOT) not in sys.path:
    sys.path.insert(0, str(_SHARED_ROOT))
import pipeline_store  # noqa: E402

PIPELINE = Path("data/pipeline.yml")


def load(path: Path):
    if not path.is_file():
        sys.exit(f"not found: {path.resolve()}\nRun this from the directory holding data/.")
    return pipeline_store.load(path)


def list_items(pipeline) -> int:
    found = False
    for company in pipeline.get("companies") or []:
        items = company.get("action_items") or []
        if not items:
            continue
        found = True
        print(f"{company.get('slug')} ({company.get('name')})")
        for item in items:
            mark = "x" if item.get("checked") else " "
            print(f"  [{mark}] {item.get('id')}: {item.get('text')}")
    if not found:
        print("no action items recorded")
    return 0


def check(pipeline, slug: str, item_id: str, path: Path) -> int:
    # Validated against the already-loaded copy so a not-found exits without taking the lock.
    company = next((c for c in pipeline.get("companies") or [] if c.get("slug") == slug), None)
    if company is None:
        sys.exit(f"no company {slug!r} in {path}. Run --list to see the slugs.")
    item = next((i for i in company.get("action_items") or [] if i.get("id") == item_id), None)
    if item is None:
        sys.exit(f"no item {item_id!r} on {slug!r}. Run --list to see the ids.")
    if item.get("checked"):
        print(f"already checked: {slug}/{item_id}")
        return 0

    today = dt.date.today().isoformat()

    def apply(data):
        for c in data.get("companies") or []:
            if c.get("slug") != slug:
                continue
            for i in c.get("action_items") or []:
                if i.get("id") != item_id:
                    continue
                i["checked"] = True
                i["checked_at"] = today
                c.setdefault("history", []).append(
                    {"date": today, "event": f"action完了: {i.get('text')}"}
                )
        return data

    updated = pipeline_store.mutate(path, apply)
    company = next(c for c in updated.get("companies") or [] if c.get("slug") == slug)
    remaining = sum(1 for i in company.get("action_items") or [] if not i.get("checked"))
    print(f"checked: {slug}/{item_id} — {remaining} remaining")
    print(path.resolve())
    return 0


def main(argv: list[str]) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    pipeline = load(PIPELINE)
    if argv and argv[0] == "--list":
        return list_items(pipeline)
    if len(argv) != 2:
        sys.exit(__doc__.strip().splitlines()[2].strip())
    return check(pipeline, argv[0], argv[1], PIPELINE)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
